apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ciumkyd0z-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ciumkyd0z-java-quarkus-gitops